### ISSUE TITLE
Exception when clients do POST /inventory/submit

### ISSUE THREAD

**Issue by ohmer1** [munki/munkiwebadmin#19]
I just installed MWA.  It seem to work (I have data on my MWA control panel).  My clients are able to call others scripts (POST /update/preflight /update/postflight and GET /inventory/hash/xxxxx) but I get error 500 when they try to do POST /inventory/submit.

This is the stacktrace I have in my Apache logs:
```
[Mon Feb 02 13:03:43 2015] [error] Internal Server Error: /inventory/submit
[Mon Feb 02 13:03:43 2015] [error] Traceback (most recent call last):
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
[Mon Feb 02 13:03:43 2015] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
[Mon Feb 02 13:03:43 2015] [error]     return view_func(*args, **kwargs)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/munkiwebadmin/inventory/views.py", line 89, in submit
[Mon Feb 02 13:03:43 2015] [error]     path=item.get('path', '')
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/fields/related.py", line 533, in create
[Mon Feb 02 13:03:43 2015] [error]     return super(RelatedManager, self.db_manager(db)).create(**kwargs)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
[Mon Feb 02 13:03:43 2015] [error]     return self.get_query_set().create(**kwargs)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/query.py", line 402, in create
[Mon Feb 02 13:03:43 2015] [error]     obj.save(force_insert=True, using=self.db)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
[Mon Feb 02 13:03:43 2015] [error]     force_update=force_update, update_fields=update_fields)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
[Mon Feb 02 13:03:43 2015] [error]     result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
[Mon Feb 02 13:03:43 2015] [error]     return insert_query(self.model, objs, fields, **kwargs)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/query.py", line 1661, in insert_query
[Mon Feb 02 13:03:43 2015] [error]     return query.get_compiler(using=using).execute_sql(return_id)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
[Mon Feb 02 13:03:43 2015] [error]     cursor.execute(sql, params)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
[Mon Feb 02 13:03:43 2015] [error]     return self.cursor.execute(sql, params)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
[Mon Feb 02 13:03:43 2015] [error]     return self.cursor.execute(query, args)
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
[Mon Feb 02 13:03:43 2015] [error]     if not self._defer_warnings: self._warning_check()
[Mon Feb 02 13:03:43 2015] [error]   File "/var/web/munki.xxxx.ca/munkiwebadmin/lib/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
[Mon Feb 02 13:03:43 2015] [error]     warn(w[-1], self.Warning, 3)
[Mon Feb 02 13:03:43 2015] [error] Warning: Incorrect string value: '\\xCC\\x81ment...' for column 'path' at row 1```

Not sure, but seem like there is something wrong because of an accentuated character.

I'm using latest MWA build.  I'm running it on an Ubuntu 12.04 server.

**Comment by milhaus** [comment]
Same issue. I'm on FreeBSD 10.0, MySQL 14.14. I'm getting tripped up on a different set of special characters though:
DatabaseError: (1366, "Incorrect string value: '\\xCE\\xA9 Key...' for column 'path' at row 1")

**Comment by milhaus** [comment]
OK, this isn't a bug in MWA or Django. This is what happens when you don't have your MySQL database set as utf8. I deleted my database and recreated it as utf8, then redid the "python manage.py syncdb" step and the problems seem to have cleared up.

**Comment by gregneagle** [comment]
Thanks for the follow-up and solution.
